.gitmodules, test/integration/molinillo_integration_test.rb
This adds the integration tests from molinillo.
~Currently failing on 4 tests, all tests with a "base" (lockfile) or conflicts are skipped.~
All tests passing. This still skips tests involving circular dependencies because pub_grub works fine with circular dependencies (I'm no sure if it would even be possible to detect them and if they are a valid concept, more thinking needed).
=> Add molinillo integration test

pub_grub.gemspec
Spotted while trying to access the home page on https://rubygems.org/gems/pub_grub.
=> Fix homepage URL

lib/pub_grub/partial_solution.rb
Hi!
I notice a warning while working on a project uses pub_grub. This PR removes the warning.
```
lib/pub_grub/partial_solution.rb:38: warning: shadowing outer local variable - assignment
```
https://buildkite.com/matthewd/gel/builds/316#78bb8343-499d-4460-bb84-798bb5f297c0
Thank you!
=> Fix shadowing outer local variable warning

lib/pub_grub.rb, lib/pub_grub/partial_solution.rb, lib/pub_grub/term.rb, lib/pub_grub/version_solver.rb
As the fences close in on more and more of stdlib becoming default gems, it seems ideal for Gel to avoid them all where-ever possible. 
I'd generally consider that a "my problem" situation, but given PubGrub's potential use cases, it seems like that might not be a unique consideration amongst its downstreams.
The proposed changes here feel like they vary somewhat in potential controversy: dropping an unused require is fine, and the Set -> Hash change is tiny enough that's it's probably okay... but Logger is a bit more involved. Let me know if you'd prefer I pull that one out.
=> Avoid default gems

lib/pub_grub/version_range.rb, test/pub_grub/version_range_test.rb
The subclass does not respond to `#min` or `#max` defined, so if `#hash`
ends up being called, it results in a crash because the parent class
defines `#hash` using these attributes.
This can happen when checking whether an incompatibility has
been previously seen, if the incompatibility includes a
`VersionRange::Empty` term.
This commit fixes the issue by explicitly defining
`VersionRange::Empty#hash`.
=> Make sure `VersionRange::Empty#hash` works

lib/pub_grub/version_range.rb, test/pub_grub/version_union_test.rb
This can come up during resolution, because `Constraint#range` can contain instances of either class, and then since 0ce5c9571bce11ddb99c55b4be1cb2e23004566b we end up in `Term#eql?` -> `Constraint#eql?` -> `range#eql?(other.range)`.
It's still super rare, because you need a `VersionUnion` for a particular package to `hash` to the same bucket as a `VersionRange` for that same package. I have seen it come up occasionally in Gel's suite -- likely because the huge union on each of the Rails dependencies has more chances to trip it -- and often enough that I stopped to investigate this time.
=> Ensure VersionRange#eql?(VersionUnion) works

lib/pub_grub/version_range.rb, lib/pub_grub/version_solver.rb, lib/pub_grub/version_union.rb
While working on migrating Bundler to use PubGrub, I'm noticing several cases where, while PubGrub resolves correctly, its result is clearly inferior to current Bundler's result and it's also slower.
Further investigation pointed to the decision making phase, where Bundler is being smarter and choosing better dependencies that led into finding a solution earlier. I found that PubGrub's documentation in dart already acknowledges that there's room for improvement here. From https://github.com/dart-lang/pub/blob/master/doc/solver.md#decision-making:
> Pub chooses the latest matching version of the package with the fewest versions that match the outstanding constraint. This tends to find conflicts earlier if any exist, since these packages will run out of versions to try more quickly. But …
=> Use better next dependency selection strategy

README.md
Noticed that the old badge wasn't resolving.
=> Update build badge from Travis to GitHub Actions

lib/pub_grub/incompatibility.rb, lib/pub_grub/package.rb, lib/pub_grub/version_constraint.rb, lib/pub_grub/version_solver.rb, test/pub_grub/package_test.rb
If a pub grub user implements its own package class, it may have its own notion of root package. As a matter of fact, PubGrub's solver can receive a custom root package (falling back to its own internal `Package.root`).
However, when internally checking whether a package is the root package, PubGrub was always hardcoding the comparison to its own `Package.root`.
This PR tries to give more flexibility here by allowing custom package classes to define a `#root?` method, and respect that during solving, while trying to keep backwards compatibility with existing package classes that don't implement this.
=> Respect root notion of custom package classes

lib/pub_grub/solve_failure.rb
In Bundler, we normally try resolution with as many locked gems as possible from the Gemfile.lock file, but if resolution fails in that "conservative mode", we automatically unlock any locked gems that cause conflicts and retry in a more "free mode". We do this by inspecting the initial solve failure and figuring out if any locked gems caused the conflicts.
Exposising SolveFailure's incompatibility is useful for this.
=> Expose `SolveFailure` incompatibility

lib/pub_grub/basic_package_source.rb, lib/pub_grub/incompatibility.rb, lib/pub_grub/version_solver.rb
In Bundler, even if PubGrub gives much better error messages, I still wanted to keep some parts of current resolution messages that look useful to me and I think added some extra clarify. For example, special messages for "meta-dependencies", like the Ruby version, or mention to Gemfile sources when versions cannot be found. So, some example of the new error messages would look like this:
```
Because every version of foo depends on requires-old-ruby >= 0
and every version of requires-old-ruby depends on Ruby < 3.1.2,
every version of foo requires Ruby < 3.1.2.
So, because Gemfile depends on foo >= 0
and current Ruby version is = 3.1.2,
version solving has failed.
```
or
```
Because the current Bundler version (2.4.0.dev) does not satisfy bundler = 0.9.1
and Gemfile depends on bundler = …
```
=> Allow customizing failure explanations

lib/pub_grub/version_union.rb, test/pub_grub/version_solver_test.rb, test/pub_grub/version_union_test.rb
Previously this would result in an error like
```
1) Error:
PubGrub::VersionUnionTest#test_intersect_empty:
NoMethodError: undefined method `max' for #<PubGrub::VersionRange::Empty (no versions)>
if !my_range.max || (other_range.max && other_range.max < my_range.max)
^^^^
/Users/deivid/Code/jhawthorn/pub_grub/lib/pub_grub/version_union.rb:122:in `intersect'
/Users/deivid/Code/jhawthorn/pub_grub/test/pub_grub/version_union_test.rb:224:in `test_intersect_empty'
```
=> Fix crash when error explanation includes empty ranges and version unions

lib/pub_grub/basic_package_source.rb, lib/pub_grub/incompatibility.rb, test/pub_grub/version_solver_test.rb
When dealing with a situation like [this one](https://github.com/dependabot-fixtures/rubygems-circular-dependency), PubGrub would previously raise an unexpected error like the following:
```
...................................F
Failure:
PubGrub::VersionSolverTest#test_circular_dependency [/Users/deivid/Code/jhawthorn/pub_grub/test/pub_grub/version_solver_test.rb:372]:
[PubGrub::SolveFailure] exception expected, not
Class: <ArgumentError>
Message: <"a dependency Incompatibility must have exactly two terms. Got [#<PubGrub::Term circular-dependency < 0>]">
---Backtrace---
/Users/deivid/Code/jhawthorn/pub_grub/lib/pub_grub/incompatibility.rb:22:in `initialize'
/Users/deivid/Code/jhawthorn/pub_grub/lib/pub_grub/basic_package_source.rb:185:in `new' …
```
=> Fix crash when dealing with circular requirements

lib/pub_grub/version_constraint.rb, test/pub_grub/version_constraint_test.rb
This is not a problem in PubGrub itself, but it should make custom integrations with PubGrub better.
While debugging some issues in Bundler, I noticed from pub_grub's debug logs, that incompatibility constraints didn't seem to be merged correctly when across versions with the same dependencies. Since I was seeing output like this:
```
derived: not autobuild >= 1.10.0.b4, < 1.10.0.rc1
derived: not autobuild >= 1.10.0.rc1, < 1.10.0.rc2
derived: not autobuild >= 1.10.0.rc2, < 1.10.0.rc3
derived: not autobuild >= 1.10.0.rc3, < 1.10.0.rc4
derived: not autobuild >= 1.10.0.rc4, < 1.10.0.rc5
derived: not autobuild >= 1.10.0.rc5, < 1.10.0.rc6
derived: not autobuild >= 1.10.0.rc6, < 1.10.0.rc7
derived: not autobuild >= 1.10.0.rc7, < 1.10.0.rc8
derived: not autobuild >= 1.10.0.rc8, < 1.10.0.rc9
``` …
=> Add a proper constraint equality

lib/pub_grub/version_range.rb, lib/pub_grub/version_union.rb, test/pub_grub/version_range_test.rb, test/pub_grub/version_union_test.rb
In Bundler, we consider "1.12.5" and "1.12.5-x86_64-linux" different for resolution purposes, but equal when representing versions in error messages and so on.
Using strict min and max equality for range string representation leads to same weird ranges reading like "< 1.12.5, > 1.12.5".
It seems best to use the equality of string representations of mix and max to decide whether to display "=" or "<, >" for representing ranges.
Similarly for version unions.
=> Use `to_s` representation of min and max when displaying ranges and unions

lib/pub_grub/basic_package_source.rb, lib/pub_grub/incompatibility.rb, lib/pub_grub/static_package_source.rb, test/pub_grub/version_solver_test.rb
The [previous approach](https://github.com/jhawthorn/pub_grub/pull/19) did not really work great in the realworld. See https://github.com/rubygems/rubygems/issues/6328.
I think it's simpler to remove these self-referencing redundant dependencies in the package source, before resolution.
=> Improve handling of self-referencing dependencies

lib/pub_grub/incompatibility.rb, test/pub_grub/version_solver_test.rb
"Forbidden" reads as overly technical and may be confusing since it's more often used as in the context of authorization. Basically it had "an illegal operation was performed" vibes 😅.
This changes the wording from "x is forbidden" to "x cannot be used", and also drops "every version of" when appropriate.
Wording suggested by @indirect
Co-authored-by: @composerinteralia
=> Use less formal wording for forbidden terms

lib/pub_grub/static_package_source.rb, test/test_helper.rb
👋 Hi, Thank you for maintaining `pub_grub`.
I got `NameError` with sample code like:
```
$ cat -p sample1.rb
require "pub_grub"
source = PubGrub::StaticPackageSource.new do |s|
s.add 'foo', '2.0.0', deps: { 'bar' => '1.0.0' }
s.add 'foo', '1.0.0'
s.add 'bar', '1.0.0', deps: { 'foo' => '1.0.0' }
s.root deps: { 'foo' => '>= 1.0.0' }
end
solver = PubGrub::VersionSolver.new(source: source)
result = solver.solve
$ ruby sample1.rb
/Users/hsbt/.local/share/gem/gems/pub_grub-0.5.0/lib/pub_grub/static_package_source.rb:50:in `parse_dependency': uninitialized constant PubGrub::RubyGems (NameError)
PubGrub::RubyGems.parse_constraint(package, dependency)
^^^^^^^^^^
```
I'm not sure why `pub_grub/rubygems.rb` is not required by `lib/pub_grub/static_package_source.rb`. But …
=> Added explicitly require for PubGrub::RubyGems

lib/pub_grub/basic_package_source.rb, lib/pub_grub/version_range.rb, test/pub_grub/version_range_test.rb, test/pub_grub/version_solver_test.rb
The current implementation of `BasicPackageSource` was sometimes creating version ranges with `min == nil`, and `include_min == true`. These are weird, and although they generally work fine, they did cause the current implementation of `VersionRange#contiguous_to?` to not work fine, and as a result version solving to fail sometimes.
Fix is https://github.com/jhawthorn/pub_grub/commit/548456352087f09354809d54aea489351bb88fd5. That brings all molinillo integration specs back to green, and fixes the issue reported in #30.
Although this is not really a resolver issue, but an issue with a specific package source, Bundler inherited this bug because its package source was based on `BasicPackageSource`.
In bd1952144bc4d09063578ce92eef2e864a5a3c9e, I also started preventing these weird ranges from …
=> Fix issue in BasicPackageSource that prevents resolution from succeeding sometimes

lib/pub_grub/version_range.rb
I found the culprit of #30 to be that sometimes BasicPackageSource creates version ranges with `min == nil` and `include_min == true` and `VersionRange#contiguous_to?` does not deal with this kind of range well, making pub grub create incorrect version unions.
I think the better fix for this #35, but this alternative implementation of `VersionRange#contiguous_to?` does not suffer from the issue and handles these strange ranges in a better way. Specific commit implementing this is 52fc70c0f530105af64e41275d43ad5448692e91.
Also built on top of #34 for green CI.
Also fixes #30.
=> Change `VersionRange#contiguous_to?` to deal better with "strange version ranges"

lib/pub_grub/version_solver.rb
Previously, `#unsatisfied` was called 6 times per `#work` iteration:
- in `#solve` to determine whether to call `#work` again
- at the beginning of `#work` to early return
- at the beginning of `#choose_package_version` to early return
- a second time in `#choose_package_version` just to find the term that matches the package returned by `#next_package_to_try`
- in `#next_package_to_try`
- at the end of `#work` to get return value
In a profile of a large app I work on, `bundle update` is spending:
- 8.8% of time in `Hash#key?` due to `#unsatisfied`
- 5.5% of time in `#unsatisfied` itself
- 3.1% of time in `Bundler::Resolver::Package#hash` due to `#unsatisfied`
- 1.9% of time in `String#hash` due to `#unsatisfied`
- 1.4% of time in `Array#reject` due to `#unsatisfied`
- 0.7% of time in …
=> Call `PartialSolution#unsatisfied` 6x less
